export const MAX_EXERCISE_TO_DO_NOTIFICATION = 99;
export const MAX_EXERCISE_IN_LEARNING_BOOKMARKS = 50;
export const MAX_BOOKMARKS_TO_STUDY_PER_ARTICLE = 10;
export const MAX_WORDS_IN_BOOKMARK_FOR_EXERCISES = 3;
