import React from "react";

function CountryFlags({ languageCode }) {
    function getFlagEmoji(languageCode) {
        const languageFlags = {
            //list generated by ChatGPT
            af: "🇦🇫", // Afghanistan
            ax: "🇦🇽", // Åland Islands
            al: "🇦🇱", // Albania
            dz: "🇩🇿", // Algeria
            as: "🇦🇸", // American Samoa
            ad: "🇦🇩", // Andorra
            ao: "🇦🇴", // Angola
            ai: "🇦🇮", // Anguilla
            ag: "🇦🇬", // Antigua & Barbuda
            ar: "🇦🇷", // Argentina
            am: "🇦🇲", // Armenia
            aw: "🇦🇼", // Aruba
            au: "🇦🇺", // Australia
            at: "🇦🇹", // Austria
            az: "🇦🇿", // Azerbaijan
            bs: "🇧🇸", // Bahamas
            bh: "🇧🇭", // Bahrain
            bd: "🇧🇩", // Bangladesh
            bb: "🇧🇧", // Barbados
            by: "🇧🇾", // Belarus
            be: "🇧🇪", // Belgium
            bz: "🇧🇿", // Belize
            bj: "🇧🇯", // Benin
            bm: "🇧🇲", // Bermuda
            bt: "🇧🇹", // Bhutan
            bo: "🇧🇴", // Bolivia
            ba: "🇧🇦", // Bosnia & Herzegovina
            bw: "🇧🇼", // Botswana
            br: "🇧🇷", // Brazil
            io: "🇮🇴", // British Indian Ocean Territory
            vg: "🇻🇬", // British Virgin Islands
            bn: "🇧🇳", // Brunei
            bg: "🇧🇬", // Bulgaria
            bf: "🇧🇫", // Burkina Faso
            bi: "🇧🇮", // Burundi
            kh: "🇰🇭", // Cambodia
            cm: "🇨🇲", // Cameroon
            ca: "🇨🇦", // Canada
            cv: "🇨🇻", // Cape Verde
            bq: "🇧🇶", // Caribbean Netherlands
            ky: "🇰🇾", // Cayman Islands
            cf: "🇨🇫", // Central African Republic
            td: "🇹🇩", // Chad
            cl: "🇨🇱", // Chile
            cn: "🇨🇳", // China
            cx: "🇨🇽", // Christmas Island
            cc: "🇨🇨", // Cocos (Keeling) Islands
            co: "🇨🇴", // Colombia
            km: "🇰🇲", // Comoros
            cg: "🇨🇬", // Congo - Brazzaville
            cd: "🇨🇩", // Congo - Kinshasa
            ck: "🇨🇰", // Cook Islands
            cr: "🇨🇷", // Costa Rica
            ci: "🇨🇮", // Côte d’Ivoire
            hr: "🇭🇷", // Croatia
            cu: "🇨🇺", // Cuba
            cw: "🇨🇼", // Curaçao
            cy: "🇨🇾", // Cyprus
            cz: "🇨🇿", // Czechia
            dk: "🇩🇰", // Denmark
            dj: "🇩🇯", // Djibouti
            dm: "🇩🇲", // Dominica
            do: "🇩🇴", // Dominican Republic
            ec: "🇪🇨", // Ecuador
            eg: "🇪🇬", // Egypt
            sv: "🇸🇻", // El Salvador
            gq: "🇬🇶", // Equatorial Guinea
            er: "🇪🇷", // Eritrea
            ee: "🇪🇪", // Estonia
            et: "🇪🇹", // Ethiopia
            fk: "🇫🇰", // Falkland Islands
            fo: "🇫🇴", // Faroe Islands
            fj: "🇫🇯", // Fiji
            fi: "🇫🇮", // Finland
            fr: "🇫🇷", // France
            gf: "🇬🇫", // French Guiana
            pf: "🇵🇫", // French Polynesia
            tf: "🇹🇫", // French Southern Territories
            ga: "🇬🇦", // Gabon
            gm: "🇬🇲", // Gambia
            ge: "🇬🇪", // Georgia
            de: "🇩🇪", // Germany
            gh: "🇬🇭", // Ghana
            gi: "🇬🇮", // Gibraltar
            gr: "🇬🇷", // Greece
            gl: "🇬🇱", // Greenland
            gd: "🇬🇩", // Grenada
            gp: "🇬🇵", // Guadeloupe
            gu: "🇬🇺", // Guam
            gt: "🇬🇹", // Guatemala
            gg: "🇬🇬", // Guernsey
            gn: "🇬🇳", // Guinea
            gw: "🇬🇼", // Guinea-Bissau
            gy: "🇬🇾", // Guyana
            ht: "🇭🇹", // Haiti
            hn: "🇭🇳", // Honduras
            hk: "🇭🇰", // Hong Kong SAR China
            hu: "🇭🇺", // Hungary
            is: "🇮🇸", // Iceland
            in: "🇮🇳", // India
            id: "🇮🇩", // Indonesia
            ir: "🇮🇷", // Iran
            iq: "🇮🇶", // Iraq
            ie: "🇮🇪", // Ireland
            im: "🇮🇲", // Isle of Man
            il: "🇮🇱", // Israel
            it: "🇮🇹", // Italy
            jm: "🇯🇲", // Jamaica
            jp: "🇯🇵", // Japan
            je: "🇯🇪", // Jersey
            jo: "🇯🇴", // Jordan
            kz: "🇰🇿", // Kazakhstan
            ke: "🇰🇪", // Kenya
            ki: "🇰🇮", // Kiribati
            xk: "🇽🇰", // Kosovo
            kw: "🇰🇼", // Kuwait
            kg: "🇰🇬", // Kyrgyzstan
            la: "🇱🇦", // Laos
            lv: "🇱🇻", // Latvia
            lb: "🇱🇧", // Lebanon
            ls: "🇱🇸", // Lesotho
            lr: "🇱🇷", // Liberia
            ly: "🇱🇾", // Libya
            li: "🇱🇮", // Liechtenstein
            lt: "🇱🇹", // Lithuania
            lu: "🇱🇺", // Luxembourg
            mo: "🇲🇴", // Macau SAR China
            mk: "🇲🇰", // Macedonia
            mg: "🇲🇬", // Madagascar
            mw: "🇲🇼", // Malawi
            my: "🇲🇾", // Malaysia
            mv: "🇲🇻", // Maldives
            ml: "🇲🇱", // Mali
            mt: "🇲🇹", // Malta
            mh: "🇲🇭", // Marshall Islands
            mq: "🇲🇶", // Martinique
            mr: "🇲🇷", // Mauritania
            mu: "🇲🇺", // Mauritius
            yt: "🇾🇹", // Mayotte
            mx: "🇲🇽", // Mexico
            fm: "🇫🇲", // Micronesia
            md: "🇲🇩", // Moldova
            mc: "🇲🇨", // Monaco
            mn: "🇲🇳", // Mongolia
            me: "🇲🇪", // Montenegro
            ms: "🇲🇸", // Montserrat
            ma: "🇲🇦", // Morocco
            mz: "🇲🇿", // Mozambique
            mm: "🇲🇲", // Myanmar (Burma)
            na: "🇳🇦", // Namibia
            nr: "🇳🇷", // Nauru
            np: "🇳🇵", // Nepal
            nl: "🇳🇱", // Netherlands
            nc: "🇳🇨", // New Caledonia
            nz: "🇳🇿", // New Zealand
            ni: "🇳🇮", // Nicaragua
            ne: "🇳🇪", // Niger
            ng: "🇳🇬", // Nigeria
            nu: "🇳🇺", // Niue
            nf: "🇳🇫", // Norfolk Island
            kp: "🇰🇵", // North Korea
            mp: "🇲🇵", // Northern Mariana Islands
            no: "🇳🇴", // Norway
            om: "🇴🇲", // Oman
            pk: "🇵🇰", // Pakistan
            pw: "🇵🇼", // Palau
            ps: "🇵🇸", // Palestinian Territories
            pa: "🇵🇦", // Panama
            pg: "🇵🇬", // Papua New Guinea
            py: "🇵🇾", // Paraguay
            pe: "🇵🇪", // Peru
            ph: "🇵🇭", // Philippines
            pn: "🇵🇳", // Pitcairn Islands
            pl: "🇵🇱", // Poland
            pt: "🇵🇹", // Portugal
            pr: "🇵🇷", // Puerto Rico
            qa: "🇶🇦", // Qatar
            re: "🇷🇪", // Réunion
            ro: "🇷🇴", // Romania
            ru: "🇷🇺", // Russia
            rw: "🇷🇼", // Rwanda
            bl: "🇧🇱", // Saint Barthélemy
            sh: "🇸🇭", // Saint Helena
            kn: "🇰🇳", // Saint Kitts & Nevis
            lc: "🇱🇨", // Saint Lucia
            mf: "🇲🇫", // Saint Martin
            pm: "🇵🇲", // Saint Pierre & Miquelon
            ws: "🇼🇸", // Samoa
            sm: "🇸🇲", // San Marino
            st: "🇸🇹", // São Tomé & Príncipe
            sa: "🇸🇦", // Saudi Arabia
            sn: "🇸🇳", // Senegal
            rs: "🇷🇸", // Serbia
            sc: "🇸🇨", // Seychelles
            sl: "🇸🇱", // Sierra Leone
            sg: "🇸🇬", // Singapore
            sx: "🇸🇽", // Sint Maarten
            sk: "🇸🇰", // Slovakia
            si: "🇸🇮", // Slovenia
            sb: "🇸🇧", // Solomon Islands
            so: "🇸🇴", // Somalia
            za: "🇿🇦", // South Africa
            gs: "🇬🇸", // South Georgia & South Sandwich Islands
            kr: "🇰🇷", // South Korea
            ss: "🇸🇸", // South Sudan
            es: "🇪🇸", // Spain
            lk: "🇱🇰", // Sri Lanka
            sd: "🇸🇩", // Sudan
            sr: "🇸🇷", // Suriname
            sj: "🇸🇯", // Svalbard & Jan Mayen
            sz: "🇸🇿", // Eswatini
            se: "🇸🇪", // Sweden
            ch: "🇨🇭", // Switzerland
            sy: "🇸🇾", // Syria
            tw: "🇹🇼", // Taiwan
            tj: "🇹🇯", // Tajikistan
            tz: "🇹🇿", // Tanzania
            th: "🇹🇭", // Thailand
            tl: "🇹🇱", // Timor-Leste
            tg: "🇹🇬", // Togo
            tk: "🇹🇰", // Tokelau
            to: "🇹🇴", // Tonga
            tt: "🇹🇹", // Trinidad & Tobago
            tn: "🇹🇳", // Tunisia
            tr: "🇹🇷", // Turkey
            tm: "🇹🇲", // Turkmenistan
            tc: "🇹🇨", // Turks & Caicos Islands
            tv: "🇹🇻", // Tuvalu
            ug: "🇺🇬", // Uganda
            ua: "🇺🇦", // Ukraine
            ae: "🇦🇪", // United Arab Emirates
            gb: "🇬🇧", // United Kingdom
            us: "🇺🇸", // United States
            uy: "🇺🇾", // Uruguay
            uz: "🇺🇿", // Uzbekistan
            vu: "🇻🇺", // Vanuatu
            va: "🇻🇦", // Vatican City
            ve: "🇻🇪", // Venezuela
            vn: "🇻🇳", // Vietnam
            wf: "🇼🇫", // Wallis & Futuna
            ye: "🇾🇪", // Yemen
            zm: "🇿🇲", // Zambia
            zw: "🇿🇼", // Zimbabwe
        };
        return languageFlags[languageCode] || "";
    }

    return <span style={{ margin: '0.5em' }}>{getFlagEmoji(languageCode)}</span>;
}

export default CountryFlags;
